//
const dummyInventory = [
  {
    id: 1,
    org_id: '316',
    item_name: 'Laptop X',
    product_id: 'prod-abc-001', // Added for consistency with models
    inventory_id: 101, // Added for consistency
    pack_units: 'PCS',
    hsn: '847130',
    rem_stock: 10,
    status: 'OK',
    // Properties that might come from 'sample' table (simulated)
    med_name: 'Laptop X',
    // Properties that might come from 'batch' table (simulated, sum of batches)
    batch_qty: 10,
    threshold: 5,
  },
  {
    id: 2,
    org_id: '316',
    item_name: 'Mouse Pro',
    product_id: 'prod-abc-002',
    inventory_id: 102,
    pack_units: 'PCS',
    hsn: '847160',
    rem_stock: 50,
    status: 'OK',
    med_name: 'Mouse Pro',
    batch_qty: 50,
    threshold: 10,
  },
  {
    id: 3,
    org_id: '316', // Different organization for testing
    item_name: 'Keyboard Mechanical',
    product_id: 'prod-def-001',
    inventory_id: 103,
    pack_units: 'PCS',
    hsn: '847160',
    rem_stock: 30,
    status: 'LOW',
    med_name: 'Keyboard Mechanical',
    batch_qty: 30,
    threshold: 40,
  },
  {
    id: 4,
    org_id: '316',
    item_name: 'Monitor UltraWide',
    product_id: 'prod-abc-003',
    inventory_id: 104,
    pack_units: 'PCS',
    hsn: '852852',
    rem_stock: 5,
    status: 'LOW',
    med_name: 'Monitor UltraWide',
    batch_qty: 5,
    threshold: 10,
  },
  {
    id: 5,
    org_id: '316',
    item_name: 'Webcam HD',
    product_id: 'prod-abc-004',
    inventory_id: 105,
    pack_units: 'PCS',
    hsn: '852580',
    rem_stock: 20,
    status: 'OK',
    med_name: 'Webcam HD',
    batch_qty: 20,
    threshold: 5,
  },
  {
    id: 6,
    org_id: '316',
    item_name: 'Headphones Wireless',
    product_id: 'prod-def-002',
    inventory_id: 106,
    pack_units: 'PCS',
    hsn: '851830',
    rem_stock: 15,
    status: 'OK',
    med_name: 'Headphones Wireless',
    batch_qty: 15,
    threshold: 5,
  },
  {
    id: 7,
    org_id: '316',
    item_name: 'USB-C Hub',
    product_id: 'prod-abc-005',
    inventory_id: 107,
    pack_units: 'PCS',
    hsn: '850440',
    rem_stock: 40,
    status: 'OK',
    med_name: 'USB-C Hub',
    batch_qty: 40,
    threshold: 10,
  },
  {
    id: 8,
    org_id: '316',
    item_name: 'SSD 1TB',
    product_id: 'prod-abc-006',
    inventory_id: 108,
    pack_units: 'PCS',
    hsn: '847170',
    rem_stock: 8,
    status: 'OK',
    med_name: 'SSD 1TB',
    batch_qty: 8,
    threshold: 2,
  },
  {
    id: 9,
    org_id: '316',
    item_name: 'External Hard Drive 2TB',
    product_id: 'prod-def-003',
    inventory_id: 109,
    pack_units: 'PCS',
    hsn: '847170',
    rem_stock: 12,
    status: 'OK',
    med_name: 'External Hard Drive 2TB',
    batch_qty: 12,
    threshold: 3,
  },
  {
    id: 10,
    org_id: '316',
    item_name: 'Router WiFi 6',
    product_id: 'prod-abc-007',
    inventory_id: 110,
    pack_units: 'PCS',
    hsn: '851762',
    rem_stock: 7,
    status: 'LOW',
    med_name: 'Router WiFi 6',
    batch_qty: 7,
    threshold: 10,
  },
  {
    id: 11,
    org_id: '316',
    item_name: 'Speaker Bluetooth',
    product_id: 'prod-abc-008',
    inventory_id: 111,
    pack_units: 'PCS',
    hsn: '851829',
    rem_stock: 25,
    status: 'OK',
    med_name: 'Speaker Bluetooth',
    batch_qty: 25,
    threshold: 5,
  },
  {
    id: 12,
    org_id: '316',
    item_name: 'Printer Laser',
    product_id: 'prod-def-004',
    inventory_id: 112,
    pack_units: 'PCS',
    hsn: '844331',
    rem_stock: 3,
    status: 'LOW',
    med_name: 'Printer Laser',
    batch_qty: 3,
    threshold: 5,
  },
  {
    id: 13,
    org_id: '316',
    item_name: 'Graphics Card RTX',
    product_id: 'prod-abc-009',
    inventory_id: 113,
    pack_units: 'PCS',
    hsn: '847330',
    rem_stock: 2,
    status: 'LOW',
    med_name: 'Graphics Card RTX',
    batch_qty: 2,
    threshold: 3,
  },
  {
    id: 14,
    org_id: '316',
    item_name: 'RAM 16GB Kit',
    product_id: 'prod-abc-010',
    inventory_id: 114,
    pack_units: 'PCS',
    hsn: '847330',
    rem_stock: 15,
    status: 'OK',
    med_name: 'RAM 16GB Kit',
    batch_qty: 15,
    threshold: 5,
  },
  {
    id: 15,
    org_id: '316',
    item_name: 'CPU Cooler',
    product_id: 'prod-def-005',
    inventory_id: 115,
    pack_units: 'PCS',
    hsn: '841590',
    rem_stock: 10,
    status: 'OK',
    med_name: 'CPU Cooler',
    batch_qty: 10,
    threshold: 2,
  },
  {
    id: 16,
    org_id: '316',
    item_name: 'Wireless Charger',
    product_id: 'prod-abc-011',
    inventory_id: 116,
    pack_units: 'PCS',
    hsn: '850440',
    rem_stock: 20,
    status: 'OK',
    med_name: 'Wireless Charger',
    batch_qty: 20,
    threshold: 5,
  },
  {
    id: 17,
    org_id: '316',
    item_name: 'External Webcam',
    product_id: 'prod-abc-012',
    inventory_id: 117,
    pack_units: 'PCS',
    hsn: '852580',
    rem_stock: 5,
    status: 'LOW',
    med_name: 'External Webcam',
    batch_qty: 5,
    threshold: 10,
  },
  {
    id: 18,
    org_id: '316',
    item_name: 'Gaming Headset',
    product_id: 'prod-abc-013',
    inventory_id: 118,
    pack_units: 'PCS',
    hsn: '851830',
    rem_stock: 12,
    status: 'OK',
    med_name: 'Gaming Headset',
    batch_qty: 12,
    threshold: 5,
  },
  {
    id: 19,
    org_id: '316',
    item_name: 'Noise-Cancelling Earbuds',
    product_id: 'prod-abc-014',
    inventory_id: 119,
    pack_units: 'PCS',
    hsn: '851830',
    rem_stock: 8,
    status: 'OK',
    med_name: 'Noise-Cancelling Earbuds',
    batch_qty: 8,
    threshold: 3,
  },
  {
    id: 20,
    org_id: '316',
    item_name: 'Smart Home Hub',
    product_id: 'prod-abc-015',
    inventory_id: 120,
    pack_units: 'PCS',
    hsn: '851762',
    rem_stock: 3,
    status: 'LOW',
    med_name: 'Smart Home Hub',
    batch_qty: 3,
    threshold: 5,
  },
];

module.exports = {
  dummyInventory,
};
